[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @neurallempire/main-site build"

[deploy]
startCommand = "pnpm --filter @neurallempire/main-site start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
