[build]
builder = "NIXPACKS"
watchPatterns = ["apps/main-site/**"]

[deploy]
startCommand = "cd apps/main-site && pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
